[project]
name = "pykitesim"
version = "0.1.0"
description = "Example for calling Julia from Python"
authors = ["Uwe Fechner <u.fechner-1@tudelft.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.8.19"
ipython = ">=7.16.1,<7.17"
numpy = ">=1.19.5,<1.20"
pandas = ">=1.1.5,<1.2"
pyquaternion = ">=0.9.9,<0.10"
matplotlib = ">=3.5.3,<3.6"
pytest = ">=8.2.2,<8.3"

